### ISSUE TITLE
Inaccurate results for trivial problems

### ISSUE THREAD

**Issue by itsmi** [rkistner/chinese-postman#13]
In a trivial case, such as

```
Start Node, End Node, Segment Length
0,1,1000.0
1,2,1000.0
2,3,1000.0
3,4,1000.0
4,5,1000.0
5,6,1000.0
6,1,1000.0
7,8,1000.0
8,9,1000.0
9,0,1000.0
0,10,1000.0
10,11,1000.0
11,7,1000.0
```

The result given by the code is 11,7,8,9,0,1,6,5,4,3,2,1,0,10,11 (cost = 14000). However, there is a shorter path that, in fact, does not require to cover lines multiple times: 1,2,3,4,5,6,1,0,9,8,7,11,10,0 (cost = 13000).

![problem1](https://user-images.githubusercontent.com/12628078/50797345-76e17600-12a2-11e9-9b42-fe515b047811.png)

**Comment by peternowee** [comment]
Actually that second route is the same as the first, just starting at a different point, going backwards and not returning to the start point. Not returning to the start point is what saves 1000.

**Comment by itsmi** [comment]
Thanks, What you say is true, but in the first (more expensive) case, the algorithm has to go back to the starting point in order to cover all lines. In the second case, it doesn't have to return, so it isn't/shouldn't be a requirement for the algorithm to return, but rather to cover all lines in the shortest path. Also, shouldn't the algorithm find the best starting point automatically?

**Comment by peternowee** [comment]
I see what you mean, but I think you are defining a new problem then, because according to the [Wikipedia-article on the Route inspection problem](https://en.wikipedia.org/w/index.php?title=Route_inspection_problem&oldid=874533937) the path has to be closed:

> [T]he Chinese postman problem (CPP), postman tour or route inspection problem is to find a shortest **closed** path or circuit that visits every edge of an (connected) undirected graph.

Still, interesting question you pose: What is the shortest route if closing the path is optional? I guess that you could just first find the closed path and then cut out the longest edge. That immediately defines the two starting/end points then.

**Comment by itsmi** [comment]
I understand -- I wasn't aware of that. Yes, that's how I implemented it. Thanks for your assistance!
