### ISSUE TITLE
cant export from qgis

### ISSUE THREAD

**Issue by vlasvlasvlas** [rkistner/chinese-postman#15]
hi! i was testing this plugin, and altough i can visualize the cpp path, i cant export any file or data from qgis layer (csv,geojson, to postgres, shp, anyhow)

![Untitled](https://user-images.githubusercontent.com/4071796/54156797-c02a7f00-4425-11e9-9405-febb500243d6.png)

why this may be? thanks.

**Comment by peternowee** [comment]
Using QGIS 2.14.11 or 2.18.28, in the Layers-panel, right-click on the `chinese_postman`-layer, Save As...

Exporting to ESRI Shapefile (.shp) and GeoJSON (.geojson) works for me. I am able to reopen each file in QGIS and see the route again.

I also tried CSV, but that resulted in almost empty files (1 or 2 bytes filesize). I doubt that is related to Chinese Postman though, given that the other export methods worked.

Same results in both QGIS 2.14.11 and 2.18.28.

So, I cannot really reproduce this. Perhaps it's because the route is on a memory layer? Perhaps in combination with some older QGIS version or some specific QGIS issue? Anyway, at first sight, this seems more like a QGIS support question to me than an actual issue with Chinese Postman.

**Comment by rkistner** [comment]
@peternowee Thanks for the input - it does look like a QGIS support question.

If there's something we need to do differently in the generated layer to make this easier, we can open another issue.
